version: '3'
services:
  edgeware:
    build:
      context: .
    ports:
      - "127.0.0.1:30355:30366/tcp"
      - "127.0.0.1:9955:9966/tcp"
    image: straightedge-sandbox:latest
    volumes:
      - ".:/data"
    command: tail -f /dev/null